// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for HomepageIntro documents */
interface HomepageIntroDocumentData {
    /**
     * TitleFirstLine field in *HomepageIntro*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepageIntro.titlefirstline
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    titlefirstline: prismicT.RichTextField;
    /**
     * Slice Zone field in *HomepageIntro*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: homepageIntro.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomepageIntroDocumentDataSlicesSlice>;
}
/**
 * Slice for *HomepageIntro → Slice Zone*
 *
 */
type HomepageIntroDocumentDataSlicesSlice = HomepageIntroSlice | ArtistSectionHeaderSlice;
/**
 * HomepageIntro document from Prismic
 *
 * - **API ID**: `homepageIntro`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageIntroDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomepageIntroDocumentData>, "homepageIntro", Lang>;
/** Content for Test documents */
interface TestDocumentData {
    /**
     * Slice Zone field in *Test*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: test.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<TestDocumentDataSlicesSlice>;
}
/**
 * Slice for *Test → Slice Zone*
 *
 */
type TestDocumentDataSlicesSlice = TextBlockSlice | ImageSlice;
/**
 * Test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TestDocumentData>, "test", Lang>;
export type AllDocumentTypes = HomepageIntroDocument | TestDocument;
/**
 * Primary content in ArtistSectionHeader → Primary
 *
 */
interface ArtistSectionHeaderSliceDefaultPrimary {
    /**
     * ArtistSectionHeaderFirstLine field in *ArtistSectionHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: artist_section_header.primary.ArtistSectionHeaderFirstLine
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    ArtistSectionHeaderFirstLine: prismicT.RichTextField;
    /**
     * ArtistSectionHeaderSecondLine field in *ArtistSectionHeader → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: artist_section_header.primary.ArtistSectionHeaderSecondLine
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    ArtistSectionHeaderSecondLine: prismicT.RichTextField;
}
/**
 * Default variation for ArtistSectionHeader Slice
 *
 * - **API ID**: `default`
 * - **Description**: `ArtistSectionHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtistSectionHeaderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ArtistSectionHeaderSliceDefaultPrimary>, never>;
/**
 * Slice variation for *ArtistSectionHeader*
 *
 */
type ArtistSectionHeaderSliceVariation = ArtistSectionHeaderSliceDefault;
/**
 * ArtistSectionHeader Shared Slice
 *
 * - **API ID**: `artist_section_header`
 * - **Description**: `ArtistSectionHeader`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ArtistSectionHeaderSlice = prismicT.SharedSlice<"artist_section_header", ArtistSectionHeaderSliceVariation>;
/**
 * Primary content in HomepageIntro → Primary
 *
 */
interface HomepageIntroSliceDefaultPrimary {
    /**
     * TitleFirstLine field in *HomepageIntro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: homepage_intro.primary.TitleFirstLine
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    TitleFirstLine: prismicT.RichTextField;
    /**
     * TitleSecondLine field in *HomepageIntro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: homepage_intro.primary.TitleSecondLine
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    TitleSecondLine: prismicT.RichTextField;
    /**
     * Description field in *HomepageIntro → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: homepage_intro.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for HomepageIntro Slice
 *
 * - **API ID**: `default`
 * - **Description**: `HomepageIntro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageIntroSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<HomepageIntroSliceDefaultPrimary>, never>;
/**
 * Slice variation for *HomepageIntro*
 *
 */
type HomepageIntroSliceVariation = HomepageIntroSliceDefault;
/**
 * HomepageIntro Shared Slice
 *
 * - **API ID**: `homepage_intro`
 * - **Description**: `HomepageIntro`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type HomepageIntroSlice = prismicT.SharedSlice<"homepage_intro", HomepageIntroSliceVariation>;
/**
 * Primary content in Image → Primary
 *
 */
interface ImageSliceDefaultPrimary {
    /**
     * Image field in *Image → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: image.primary.image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    image: prismicT.ImageField<never>;
}
/**
 * Default variation for Image Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<ImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *Image*
 *
 */
type ImageSliceVariation = ImageSliceDefault;
/**
 * Image Shared Slice
 *
 * - **API ID**: `image`
 * - **Description**: `Image`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type ImageSlice = prismicT.SharedSlice<"image", ImageSliceVariation>;
/**
 * Primary content in TextBlock → Primary
 *
 */
interface TextBlockSliceDefaultPrimary {
    /**
     * Title field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: text_block.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Description field in *TextBlock → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: A nice description of your feature
     * - **API ID Path**: text_block.primary.description
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    description: prismicT.RichTextField;
}
/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TextBlockSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TextBlock*
 *
 */
type TextBlockSliceVariation = TextBlockSliceDefault;
/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: `TextBlock`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TextBlockSlice = prismicT.SharedSlice<"text_block", TextBlockSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomepageIntroDocumentData, HomepageIntroDocumentDataSlicesSlice, HomepageIntroDocument, TestDocumentData, TestDocumentDataSlicesSlice, TestDocument, AllDocumentTypes, ArtistSectionHeaderSliceDefaultPrimary, ArtistSectionHeaderSliceDefault, ArtistSectionHeaderSliceVariation, ArtistSectionHeaderSlice, HomepageIntroSliceDefaultPrimary, HomepageIntroSliceDefault, HomepageIntroSliceVariation, HomepageIntroSlice, ImageSliceDefaultPrimary, ImageSliceDefault, ImageSliceVariation, ImageSlice, TextBlockSliceDefaultPrimary, TextBlockSliceDefault, TextBlockSliceVariation, TextBlockSlice };
    }
}
