services:
  web:
    image: web
    build:
      context: ../../
      dockerfile: apps/web/Dockerfile
    ports:
      - '3333:3333'
  gateway:
    image: gateway
    build:
      context: ../../
      dockerfile: apps/Tatuaz.Gateway.Api/Dockerfile
    ports:
      - '6969:80'
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '15432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
