# use tilt up -- --mode 
config.define_bool('debug')
cfg = config.parse()
debug = cfg.get('debug', False)

if debug == True:
    gateway_dockerfile = '../../apps/Tatuaz.Gateway.Api/Dockerfile.Debug'
else:
    gateway_dockerfile = '../../apps/Tatuaz.Gateway.Api/Dockerfile'

docker_build(
    'tatuaz/gateway',
    '../../',
    entrypoint=['dotnet', 'Tatuaz.Gateway.Api.dll'],
    dockerfile=gateway_dockerfile,
    only='apps/Tatuaz.Gateway.Api',
    live_update=[
        sync('../../apps/Tatuaz.Gateway.Api/out', '/app/out'),
    ],
)

docker_build(
    'tatuaz/web',
    '../../',
    entrypoint=['npm', 'start'],
    dockerfile='../../apps/web/Dockerfile',
    only=['apps/web', 'dist/apps/web'],
    live_update=[
        sync('../../apps/web/out', '/app/out'),
    ],
)

k8s_yaml([
    'kubernetes/gateway.yaml',
    'kubernetes/web.yaml',
    'kubernetes/rabbitmq.yaml',
    'kubernetes/postgresql.yaml',
    'kubernetes/postgresql-volume.yaml',
    'kubernetes/postgresql-volume-claim.yaml',
    'kubernetes/postgresql-config-map.yaml',
])

k8s_resource('gateway', port_forwards='8080:80', labels='backend')
k8s_resource('web', port_forwards='3333:3333', labels='frontend')
k8s_resource('rabbitmq', port_forwards=['5672:5672', '15672:15672'], labels='backend')
k8s_resource('postgresql', port_forwards='5432:5432', labels='backend')