apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: tatuaz-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azurestorage-azurite
          ports:
            - containerPort: 10000
