apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: tatuaz-dev
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway
          command: ["npx", "nx", "run", "gateway:serve"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: gateway-config-map
            - configMapRef:
                name: auth-config-map
            - configMapRef:
                name: swagger-config-map
            - configMapRef:
                name: rabbitmq-config-map
