apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
  namespace: tatuaz-dev
spec:
  selector:
    matchLabels:
      app: history
  replicas: 1
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: history
          command: ["npx", "nx", "run", "history:serve"]
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: history-config-map
            - configMapRef:
                name: rabbitmq-config-map
