apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: tatuaz-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgis/postgis:15-master
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgresql-config-map
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresqldata
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
        limits:
          cpu: 500m
          memory: 1Gi
      volumes:
        - name: postgresqldata
          persistentVolumeClaim:
            claimName: postgresql-volume-claim
