apiVersion: v1
kind: Service
metadata:
    name: "tatuazdevtest1-49c1"
    labels:
        app: "tatuazdevtest1-49c1"
spec:
    type: LoadBalancer
    ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
      name: http
    selector:
        app: "tatuazdevtest1-49c1"