apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-volume-claim
  namespace: tatuaz-dev
  labels:
    app: rabbitmq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
