apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-volume
  namespace: tatuaz-dev
  labels:
    type: local
    app: rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/rabbitmq"
