apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: tatuaz-dev
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: tatuaz-main
          command: ['npx', 'nx', 'run', 'Tatuaz.Gateway.Api:serve']
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: gateway-config-map
