apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-poc
  namespace: tatuaz-dev
spec:
  selector:
    matchLabels:
      app: integration-poc
  replicas: 1
  template:
    metadata:
      labels:
        app: integration-poc
    spec:
      containers:
        - name: integration-poc
          image: tatuaz-main
          command: ['npx', 'nx', 'run', 'integration-poc:serve']
          envFrom:
            - configMapRef:
                name: integration-poc-config-map
