apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-volume-claim
  namespace: tatuaz-dev
  labels:
    app: postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
