apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: tatuaz-dev
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: masstransit/rabbitmq:latest
      ports:
        - containerPort: 5672
        - containerPort: 15672
