apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: tatuaz-dev
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgresql
