// This file is generated by Slice Machine. Update with care!

import ArtistsCarousel from "./ArtistsCarousel"
import ArtistSectionHeader from "./ArtistSectionHeader"
import FaqsSection from "./FaqsSection"
import HomepageIntro from "./HomepageIntro"
import HomepagePhotos from "./HomepagePhotos"
import Image from "./Image"
import TextBlock from "./TextBlock"

export {
  ArtistSectionHeader,
  ArtistsCarousel,
  FaqsSection,
  HomepageIntro,
  HomepagePhotos,
  Image,
  TextBlock,
}

export const components = {
  artist_section_header: ArtistSectionHeader,
  artists_carousel: ArtistsCarousel,
  faqs_section: FaqsSection,
  homepage_intro: HomepageIntro,
  homepage_photos: HomepagePhotos,
  image: Image,
  text_block: TextBlock,
}
