// This file is generated by Slice Machine. Update with care!

import ArtistSectionHeader from "./ArtistSectionHeader"
import FaqsSection from "./FAQsSection"
import HomepageIntro from "./HomepageIntro"
import HomepagePhotos from "./HomepagePhotos"
import Image from "./Image"
import TextBlock from "./TextBlock"

export {
  ArtistSectionHeader,
  FaqsSection,
  HomepageIntro,
  HomepagePhotos,
  Image,
  TextBlock,
}

export const components = {
  artist_section_header: ArtistSectionHeader,
  faqs_section: FaqsSection,
  homepage_intro: HomepageIntro,
  homepage_photos: HomepagePhotos,
  image: Image,
  text_block: TextBlock,
}
