// This file is generated by Slice Machine. Update with care!

import ArtistSectionHeader from "./ArtistSectionHeader"
import HomepageIntro from "./HomepageIntro"
import HomepagePhotos from "./HomepagePhotos"
import Image from "./Image"
import TextBlock from "./TextBlock"

export {
  ArtistSectionHeader,
  HomepageIntro,
  HomepagePhotos,
  Image,
  TextBlock,
  // TotalStats,
}

export const components = {
  artist_section_header: ArtistSectionHeader,
  homepage_intro: HomepageIntro,
  homepage_photos: HomepagePhotos,
  image: Image,
  text_block: TextBlock,
  // total_stats: TotalStats,
}
