// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodaTime;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tatuaz.History.DataAccess;

#nullable disable

namespace Tatuaz.History.DataAccess.Migrations
{
    [DbContext(typeof(HistDbContext))]
    partial class HistDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.General.HistEmailInfo", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<string>("EmailType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email_type");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("error");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ObjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("object_id");

                    b.Property<Instant>("OrderedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ordered_at");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient_email");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<Instant?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.HasKey("HistId")
                        .HasName("pk_h_email_info");

                    b.ToTable("H_email_info", "H_general");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Identity.HistTatuazRole", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.HasKey("HistId")
                        .HasName("pk_h_tatuaz_roles");

                    b.ToTable("H_tatuaz_roles", "H_identity");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Identity.HistTatuazUser", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<string>("Auth0Id")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("auth0id");

                    b.Property<Guid?>("BackgroundPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("background_photo_id");

                    b.Property<Guid?>("ForegroundPhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("foreground_photo_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<string>("Id")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("HistId")
                        .HasName("pk_h_tatuaz_users");

                    b.ToTable("H_tatuaz_users", "H_identity");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Identity.HistTatuazUserRole", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_email");

                    b.HasKey("HistId")
                        .HasName("pk_h_tatuaz_user_roles");

                    b.ToTable("H_tatuaz_user_roles", "H_identity");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Photo.HistCategory", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("ImageUri")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("image_uri");

                    b.Property<int>("Popularity")
                        .HasColumnType("integer")
                        .HasColumnName("popularity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("HistId")
                        .HasName("pk_h_categories");

                    b.ToTable("H_categories", "H_photo");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Photo.HistPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Instant>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<Guid>("HistId")
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<Instant>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modified_by");

                    b.HasKey("Id")
                        .HasName("pk_h_photos");

                    b.ToTable("H_photos", "H_photo");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Photo.HistPhotoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<Guid>("HistId")
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<Guid>("PhotoId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_id");

                    b.HasKey("Id")
                        .HasName("pk_h_photo_categories");

                    b.ToTable("H_photo_categories", "H_photo");
                });

            modelBuilder.Entity("Tatuaz.Shared.Domain.Entities.Hist.Models.Photo.HistUserCategory", b =>
                {
                    b.Property<Guid>("HistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("hist_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<Instant>("HistDumpedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hist_dumped_at");

                    b.Property<int>("HistState")
                        .HasColumnType("integer")
                        .HasColumnName("hist_state");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("user_id");

                    b.HasKey("HistId")
                        .HasName("pk_h_user_categories");

                    b.ToTable("H_user_categories", "H_photo");
                });
#pragma warning restore 612, 618
        }
    }
}
