name: acr-push

on:
  push:
    branches:
      - main
      - task/TA-90-azure-deploy

jobs:
  build-push-gateway:
    name: Build and push gateway image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: apps/Tatuaz.Gateway/Dockerfile
          push: true
          tags: ${{ secrets.ACR_ENDPOINT }}/gateway:latest
          cache-from: type=registry,ref=${{ secrets.ACR_ENDPOINT }}/gateway:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_ENDPOINT }}/gateway:buildcache,mode=max