name: Web CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      number-of-agents: 2
      init-commands: |
        npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=2
      parallel-commands: |
        npx nx-cloud record -- npx nx workspace-lint
        npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        npx nx affected --target=lint --parallel=3
        npx nx affected --target=build --parallel=3
  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 2
  tests-with-npgsql:
    name: Nx Cloud - Postgres Tests
    needs: main
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
      name: Install Dependencies
        run: npm ci
      name: Run Tests
        run: npx nx affected --target=test --parallel=3
        env:
          InfrastructureTest_ConnectionStrings__Default: Server=postgres;Port=5432;Database=tatuaz-infrastructure-test-db;User Id=postgres;Password=password;
