name: Web CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job

    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.6
    with:
      number-of-agents: 3
      init-commands: |
        cd web && npx nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        cd web && npx nx-cloud record -- npx nx workspace-lint
        cd web && npx nx-cloud record -- npx nx format:check
      parallel-commands-on-agents: |
        cd web && npx nx affected --target=lint --parallel=3
        cd web && npx nx affected --target=test --parallel=3 --ci --code-coverage
        cd web && npx nx affected --target=build --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
    with:
      number-of-agents: 3
