name: Web CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgis/postgis:15-master
        env:
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Install dotnet csharpier
        run: dotnet tool install -g csharpier

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0

      - name: Install Dependencies
        run: pnpm install

      - name: Lint workspace
        run: npx nx workspace-lint

      - name: Format
        run: npx nx format:check

      - name: Lint affected
        run: npx nx affected --target=lint --parallel=3 --output-style=stream

      - name: Build affected
        run: npx nx affected --target=build --parallel=3 --output-style=stream

      - name: Test affected
        run: npx nx affected --target=test --parallel=3 --output-style=stream
